# Generated by Django 4.2.7 on 2025-05-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_achievement_rename_progress_studentprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.test', verbose_name='Тест'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('student', 'lesson', 'test')},
        ),
    ]
