# Generated by Django 5.2 on 2025-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_exercise_lesson_expected_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True, verbose_name='Термин')),
                ('definition_en', models.TextField(verbose_name='Определение (English)')),
                ('definition_ru', models.TextField(verbose_name='Определение (Русский)')),
                ('definition_cn', models.TextField(blank=True, null=True, verbose_name='Определение (中文)')),
                ('example_code', models.TextField(blank=True, verbose_name='Пример кода')),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Термины',
            },
        ),
    ]
