# Generated by Django 4.2.7 on 2025-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_expected_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('text', 'Текстовый ответ')], default='single', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='term',
            name='definition_cn',
            field=models.TextField(blank=True, null=True, verbose_name='Определение (Spanish)'),
        ),
    ]
